#pragma once
#include <stdint.h>
extern uint32_t address;
extern const unsigned short mouse[256];
extern const unsigned short Trophy[900];
extern const unsigned short iconBoot[2500];
extern const unsigned short ArchPic[4900];
extern const uint8_t font8x8_THIN[128][8];
extern unsigned char font8x16[][16];
extern const char scancode_to_ascii[128];
extern const char scancode_to_ascii_shift[128];
extern int is_extended;
extern int opened;
extern int window_count;
extern int mouse_x;
extern int mouse_y;
extern int mouseDown;
extern int velox;
extern int veloy;
extern int winX;
extern int winY;
extern int active_window;
extern int drag_offset_x;
extern int drag_offset_y;
extern int prev_mouseDown;
extern int transUI;
extern int runned959;
extern int Origin;
extern uint32_t buffer_index;
extern uint16_t windows[100][5];
extern uint16_t buttonStates[100];
extern uint16_t *disp;
extern uint16_t x;
extern uint16_t y;
extern uint16_t bx[10];
extern uint16_t by[10];
extern uint16_t bdx[10]; 
extern uint16_t bdy[10];
extern uint16_t bcol[10]; 
extern uint16_t currX;
extern uint16_t currY;
extern uint16_t *console_buffer; 
extern uint16_t line; 
extern uint16_t inputBufferIndex; 
extern uint16_t inputBuffer[60];
extern uint8_t mouse_bytes[3];
extern uint8_t shift_held; 
extern uint8_t done; 
extern uint8_t mouse_cycle; 
extern uint8_t forthistime0; 
extern uint8_t forthistime1;
extern uint8_t startOpened;
extern uint8_t runned;
extern uint8_t last_scancode; 
extern uint8_t last_scancode1;
extern uint8_t Wallpaper;
extern char title[];
extern char title1[]; 
extern char title2[];
extern char title3[];
extern char People[];
extern char time[9];
extern char *window_title_ptrs[100];