name: Build BrenmaxOS

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Download i686-elf Toolchain
        shell: powershell
        run: |
          $url = "https://github.com/lordmilko/i686-elf-tools/releases/latest/download/i686-elf-tools-windows.zip"

          Write-Host "Downloading toolchain..."
          curl.exe -L $url -o toolchain.zip

          Write-Host "Extracting..."
          Expand-Archive toolchain.zip -DestinationPath toolchain

          "$PWD\toolchain\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
      - name: Verify Compiler
        run: |
          i686-elf-gcc --version
          i686-elf-objcopy --version
          nasm -v

      - name: Build
        shell: bash
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrenmaxOS
          path: BrenmaxOS.img

      - name: Generate Release Tag
        id: tag
        shell: powershell
        run: |
          $date = Get-Date -Format "dd-MM-yy"
          $base = "Release-$date"

          $existing = git tag

          $version = 1
          $tag = $base

          while ($existing -contains $tag) {
            $version++
            $tag = "$base-v$version"
          }

          echo "tag=$tag" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          files: BrenmaxOS.img
