name: Build BrenmaxOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Download i686-elf Toolchain
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/lordmilko/i686-elf-tools/releases/download/13.2.0/i686-elf-tools-windows.zip" `
            -OutFile "toolchain.zip"

          Expand-Archive toolchain.zip -DestinationPath toolchain

          echo "$pwd\toolchain\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify Compiler
        run: |
          i686-elf-gcc --version
          i686-elf-objcopy --version
          nasm -v

      - name: Build
        shell: bash
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrenmaxOS
          path: BrenmaxOS.img

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          files: BrenmaxOS.img
